project:
  type: book
  output-dir: docs

book:
  title: "quant_methods"
  author: "Julia Cardwell"
  date: "10/22/2025"
  chapters:
    - index.qmd
    - syllabus.qmd
    - schedule.qmd
    - competencies.qmd
    - basic_R.qmd
    - command.qmd
    - describing_data.qmd
    - tmap.qmd
    - describing_spatial_data.qmd
    - labs.qmd

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

